# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100, null=True)),
                ('pdf', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=3000, null=True)),
                ('remark_id', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100, null=True)),
                ('pdf', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=3000, null=True)),
                ('remark_id', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100, null=True)),
                ('pdf', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=3000, null=True)),
                ('remark_id', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tornado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('images', models.CharField(max_length=100, null=True)),
                ('pdf', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=3000, null=True)),
                ('remark_id', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myWeb.Category')),
            ],
        ),
    ]
